{"timestamp":"2025-07-07T02:06:47.847183","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-07T02:06:47.848511","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/email_operator_test.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-07T02:06:47.908239Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T02:06:47.908672Z","level":"info","event":" Previous state of the Task instance: queued","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T02:06:47.909336Z","level":"info","event":"Current task name:send_email_task","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T02:06:47.909636Z","level":"info","event":"Dag name:email_notify_dag_test","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T02:06:47.885333","level":"info","event":"Secrets backends loaded for worker","count":1,"backend_classes":["EnvironmentVariablesBackend"],"logger":"supervisor"}
{"timestamp":"2025-07-07T02:06:47.928002","level":"info","event":"Email alerting: attempt 1","logger":"airflow.utils.email"}
{"timestamp":"2025-07-07T02:06:47.929775","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"ConnectionRefusedError","exc_value":"[Errno 111] Connection refused","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/email_operator_test.py","lineno":7,"name":"notify_email"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py","lineno":79,"name":"send_email"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py","lineno":154,"name":"send_email_smtp"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py","lineno":263,"name":"send_mime_email"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py","lineno":306,"name":"_get_smtp_connection"},{"filename":"/usr/local/lib/python3.12/smtplib.py","lineno":255,"name":"__init__"},{"filename":"/usr/local/lib/python3.12/smtplib.py","lineno":341,"name":"connect"},{"filename":"/usr/local/lib/python3.12/smtplib.py","lineno":312,"name":"_get_socket"},{"filename":"/usr/local/lib/python3.12/socket.py","lineno":865,"name":"create_connection"},{"filename":"/usr/local/lib/python3.12/socket.py","lineno":850,"name":"create_connection"}]}]}
{"timestamp":"2025-07-07T02:06:47.931916Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T02:06:47.932274Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T02:06:47.932588Z","level":"info","event":"Task:<Task(PythonOperator): send_email_task>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T02:06:47.932838Z","level":"info","event":"Failure caused by [Errno 111] Connection refused","chan":"stdout","logger":"task"}
